services:
  speedtest-exporter:
    image: speedtest-exporter
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      - SPEEDTEST_PORT=9798
    ports:
      - $SPEEDTEST_PORT:$SPEEDTEST_PORT 
