services:
  speedtest-exporter:
    image: speedtest-exporter
    build:
      context: .
      dockerfile: ./Dockerfile
    command: ["sh", "-c", "pip install debugpy -t /tmp && python /tmp/debugpy --listen 0.0.0.0:5678 -m flask run --no-debugger --no-reload --host 0.0.0.0 --port 9798"]
    ports:
      - 9798:9798
      - 5678:5678
    environment:
      - FLASK_APP=speedtest-exporter-app.webapp
