{
 "title": "jimmydoh/speedtest-exporter Example",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Throughput",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 17, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "avg(speedtest_download_bits_per_second{})",
     "legendFormat": "Download"
    },
    {
     "expr": "avg(speedtest_upload_bits_per_second{})",
     "legendFormat": "Upload"
    }
   ]
  },
  {
   "title": "Download",
   "type": "stat",
   "gridPos": { "h": 5, "w": 7, "x": 17, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(max_over_time(speedtest_download_bits_per_second[1w:5m]))",
     "legendFormat": "Best"
    },
    {
     "expr": "min(min_over_time(speedtest_download_bits_per_second[1w:5m]))",
     "legendFormat": "Worst"
    },
    {
     "expr": "avg(avg_over_time(speedtest_download_bits_per_second[1w:5m]))",
     "legendFormat": "Avg"
    }
   ]
  },
  {
   "title": "Upload",
   "type": "stat",
   "gridPos": { "h": 5, "w": 7, "x": 17, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(max_over_time(speedtest_upload_bits_per_second[1w:5m]))",
     "legendFormat": "Best"
    },
    {
     "expr": "min(min_over_time(speedtest_upload_bits_per_second[1w:5m]))",
     "legendFormat": "Worst"
    },
    {
     "expr": "avg(avg_over_time(speedtest_upload_bits_per_second[1w:5m]))",
     "legendFormat": "Avg"
    }
   ]
  },
  {
   "title": "Latency",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 17, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "avg(speedtest_ping_latency_milliseconds{})",
     "legendFormat": "Latency"
    }
   ]
  },
  {
   "title": "Latency",
   "type": "stat",
   "gridPos": { "h": 5, "w": 7, "x": 17, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "min(min_over_time(speedtest_ping_latency_milliseconds[1w:5m]))",
     "legendFormat": "Best"
    },
    {
     "expr": "max(max_over_time(speedtest_ping_latency_milliseconds[1w:5m]))",
     "legendFormat": "Worst"
    },
    {
     "expr": "avg(avg_over_time(speedtest_ping_latency_milliseconds[1w:5m]))",
     "legendFormat": "Avg"
    }
   ]
  },
  {
   "title": "Test Results",
   "type": "table",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 15 },
   "targets": [
    {
     "expr": "speedtest_download_bits_per_second"
    },
    {
     "expr": "speedtest_upload_bits_per_second"
    },
    {
     "expr": "speedtest_ping_latency_milliseconds",
     "legendFormat": "Latency"
    }
   ]
  }
 ]
}